spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LibraryTask;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 1111
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

server:
  port: 8086

testing:
  app:
    secret: secret-key
    lifetime: 60000
